#!/usr/bin/env php
<?php

require './vendor/autoload.php';

use Console\CommandRegistry;
use Inspira\Console\Console;
use Inspira\Console\Contracts\CommandRegistryInterface;
use Inspira\Console\Contracts\InputInterface;
use Inspira\Console\Contracts\OutputInterface;
use Inspira\Console\Input;
use Inspira\Console\Output;
use Inspira\Framework\Application;

$app = new Application();

$app->setBasePath('./')
    ->runAppOnConsole()
    ->boot()
    ->start();

$input = new Input();
$output = new Output();
$registry = new CommandRegistry();
$registry->register();

$app->singleton(InputInterface::class, fn() => $input);
$app->singleton(OutputInterface::class, fn() => $output);
$app->singleton(CommandRegistryInterface::class, fn() => $registry);

(new Console($app, $input, $output, $registry))->run();
exit(0);
